// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS0PGU2A-pxGFxtn19CL73jglwB1QKooY',
    appId: '1:400418295489:web:ec6c0c556e6e7b4f358e40',
    messagingSenderId: '400418295489',
    projectId: 'coursemind-b6f0a',
    authDomain: 'coursemind-b6f0a.firebaseapp.com',
    storageBucket: 'coursemind-b6f0a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB5vpK1B4bWuEN69rxo3zxwIJ8-PJlCKc',
    appId: '1:400418295489:android:e5ff49ae259811d8358e40',
    messagingSenderId: '400418295489',
    projectId: 'coursemind-b6f0a',
    storageBucket: 'coursemind-b6f0a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEiSFvZjuKUCYYTrech1jl5gsVZyzehA0',
    appId: '1:381720251752:ios:33bff9b1290fb81e1bdadd',
    messagingSenderId: '381720251752',
    projectId: 'coursemind-e4dff',
    storageBucket: 'coursemind-e4dff.firebasestorage.app',
    iosClientId: '381720251752-uv4ejjpsk3n57pqk7e1v60cm4he3ru3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.coursemind',
  );
}
